### ISSUE TITLE
Doc specifies iterable for Client methods but requires list/set

### ISSUE THREAD

**Issue by remingtonc** [cisco-ie/cisco-gnmi-python#37]
We  should accept any Iterable ([or iterator?](https://docs.python.org/2.7/glossary.html#term-iterator)).

e.g.
https://github.com/cisco-ie/cisco-gnmi-python/blob/0262b78a3098ab8c2794b5bb68dad3dde6ea96f3/src/cisco_gnmi/client.py#L155

**Comment by miott** [comment]
xe.py line 204 produces a "map" object which then fails the check for a type ``list or set``.
How about:
```
try:
    iter(paths)
except TypeError:
    raise Exception("paths must be an iterable containing Path(s)!")
```
