### ISSUE TITLE
The check_configs function only works with one update config.

### ISSUE THREAD

**Issue by miott** [cisco-ie/cisco-gnmi-python#39]
The "name" parameter is a hardcoded string called from create_updates so it will always go to this if:
```
        def check_configs(name, configs):
            if isinstance(name, string_types):
                logging.debug("Handling %s as JSON string.", name)
                try:
                    configs = json.loads(configs)
                except:
                    raise Exception("{name} is invalid JSON!".format(name=name))
                configs = [configs]
```
The "configs" variable can only be one dict for json.loads unless you put it in a list, but if you do, the configs list is then deposited into another list.

**Comment by remingtonc** [comment]
Are you referring to `check_configs` in `set_json` in `xe.py`? I think you're correct - the logic here looks like it might be inherently broken. I think the intention is to check the type of `configs` instead of `name` in those conditionals.
