### ISSUE TITLE
Rename repository to cisco-gnmi-python?

### ISSUE THREAD

**Issue by remingtonc** [cisco-ie/cisco-gnmi-python#6]
There is Cisco-specific code within this repository, should we rename and publish as `cisco_gnmi`?

**Comment by remingtonc** [comment]
Going to rename.

**Comment by remingtonc** [comment]
Wait, I don't have permission to rename. @skkumaravel are you able to rename to `cisco-gnmi-python`?

**Comment by skkumaravel** [comment]
Nope. Rekha removed all our permissions to do so. She will need to do so.

**Comment by remingtonc** [comment]
@rekharawat Please rename this repository to `cisco-gnmi-python`.

**Comment by remingtonc** [comment]
Thank you @rekharawat.
